"""initialize tables

Revision ID: 7c5ebbef717c
Revises:
Create Date: 2025-12-14 15:18:37.355742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c5ebbef717c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "country",
            sa.Enum(
                "ALBANIA",
                "ANDORRA",
                "ARMENIA",
                "AUSTRIA",
                "AZERBAIJAN",
                "BELARUS",
                "BELGIUM",
                "BOSNIA_AND_HERZEGOVINA",
                "BULGARIA",
                "CROATIA",
                "CYPRUS",
                "CZECHIA",
                "DENMARK",
                "ESTONIA",
                "FINLAND",
                "FRANCE",
                "GEORGIA",
                "GERMANY",
                "GREECE",
                "HUNGARY",
                "ICELAND",
                "IRELAND",
                "ITALY",
                "KAZAKHSTAN",
                "KOSOVO",
                "LATVIA",
                "LIECHTENSTEIN",
                "LITHUANIA",
                "LUXEMBOURG",
                "MALTA",
                "MOLDOVA",
                "MONACO",
                "MONTENEGRO",
                "NETHERLANDS",
                "NORTH_MACEDONIA",
                "NORWAY",
                "POLAND",
                "PORTUGAL",
                "ROMANIA",
                "RUSSIA",
                "SAN_MARINO",
                "SERBIA",
                "SLOVAKIA",
                "SLOVENIA",
                "SPAIN",
                "SWEDEN",
                "SWITZERLAND",
                "TURKEY",
                "UKRAINE",
                "UNITED_KINGDOM",
                "VATICAN_CITY",
                name="country",
            ),
            nullable=False,
        ),
        sa.Column(
            "continent",
            sa.Enum(
                "AFRICA", "ANTARCTICA", "ASIA", "EUROPE", "NORTH_AMERICA", "OCEANIA", "SOUTH_AMERICA", name="continent"
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.String(), nullable=False),
        sa.Column("longitude", sa.String(), nullable=False),
        sa.Column("map_image", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correct_city_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["correct_city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guessed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("game_id", sa.UUID(), nullable=True),
        sa.Column("city_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guesses")
    op.drop_table("games")
    op.drop_table("cities")
    # ### end Alembic commands ###
